---
abstract: 'automate the git steps required for a deploying code from a git repository'
author:
  - 'Ævar Arnfjörð Bjarmason <avarab@gmail.com>, Yves Orton <demerphq@gmail.com>'
build_requires:
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: git-deploy
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  Exporter: 0
  Fcntl: 0
  File::Basename: 0
  File::Find: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  Memoize: 0
  POSIX: 0
  Pod::Usage: 0
  Sys::Hostname: 0
  Term::ReadLine: 0
  Time::HiRes: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/git-deploy/git-deploy/issues
  homepage: http://git-deploy.github.com
  license: http://dev.perl.org/licenses/
  repository: https://github.com/git-deploy/git-deploy.git
version: 6.00
